import { Router } from 'express';
import meRoutes from './me.routes';
import attendanceRoutes from './attendance.routes';
import configRoutes from './config.routes';
import locationsRoutes from './locations.routes';
import insurance_companiesRoutes from './insurance-companies.routes';
import custody_typesRoutes from './custody-types.routes';
import job_titlesRoutes from './job-titles.routes';
import jobLevelsRoutes from './job-levels.routes';
import archive_reasonsRoutes from './archive-reasons.routes';
import health_syncRoutes from './health-sync.routes';
import employees_1Routes from './employees-1.routes';
import employees_2Routes from './employees-2.routes';
import employees_3Routes from './employees-3.routes';
import employees_4Routes from './employees-4.routes';
import employees_5Routes from './employees-5.routes';
import employees_6Routes from './employees-6.routes';
import employees_7Routes from './employees-7.routes';
import orgChartRoutes from './org-chart.routes';
import shifts_1Routes from './shifts-1.routes';
import shifts_2Routes from './shifts-2.routes';
import shift_assignments_1Routes from './shift-assignments-1.routes';
import shift_assignments_2Routes from './shift-assignments-2.routes';
import shift_grid_1Routes from './shift-grid-1.routes';
import shift_grid_2Routes from './shift-grid-2.routes';
import shift_grid_3Routes from './shift-grid-3.routes';
import shift_grid_4Routes from './shift-grid-4.routes';
import shift_grid_5Routes from './shift-grid-5.routes';
import shift_grid_6Routes from './shift-grid-6.routes';
import shift_grid_7Routes from './shift-grid-7.routes';
import shift_grid_8Routes from './shift-grid-8.routes';
import payroll_1Routes from './payroll-1.routes';
import payroll_2Routes from './payroll-2.routes';
import payroll_3Routes from './payroll-3.routes';
import payroll_4Routes from './payroll-4.routes';
import deductions_1Routes from './deductions-1.routes';
import deductions_2Routes from './deductions-2.routes';
import advances_1Routes from './advances-1.routes';
import advances_2Routes from './advances-2.routes';
import advanceRequestsRoutes from './advance-requests.routes';
import branchManagersRoutes from './branch-managers.routes';
import requests_1Routes from './requests-1.routes';
import requests_2Routes from './requests-2.routes';
import hiringRoutes from './hiring.routes';
import hr_reportsRoutes from './hr-reports.routes';
import shift_grid_mergeRoutes from './shift-grid-merge.routes';
import auditRoutes from './audit.routes';
import assistantRoutes from './assistant.routes';
import mobilePunchRoutes from './mobile-punch.routes';

const router = Router();
router.use(meRoutes);
router.use(auditRoutes);
router.use(assistantRoutes);
router.use(mobilePunchRoutes);
router.use(attendanceRoutes);
router.use(configRoutes);
router.use(locationsRoutes);
router.use(insurance_companiesRoutes);
router.use(custody_typesRoutes);
router.use(job_titlesRoutes);
router.use(jobLevelsRoutes);
router.use(archive_reasonsRoutes);
router.use(health_syncRoutes);
router.use(employees_1Routes);
router.use(employees_2Routes);
router.use(employees_3Routes);
router.use(employees_4Routes);
router.use(employees_5Routes);
router.use(employees_6Routes);
router.use(employees_7Routes);
router.use(orgChartRoutes);
router.use(shifts_1Routes);
router.use(shifts_2Routes);
router.use(shift_assignments_1Routes);
router.use(shift_assignments_2Routes);
router.use(shift_grid_1Routes);
router.use(shift_grid_2Routes);
router.use(shift_grid_3Routes);
router.use(shift_grid_4Routes);
router.use(shift_grid_5Routes);
router.use(shift_grid_6Routes);
router.use(shift_grid_7Routes);
router.use(shift_grid_8Routes);
router.use(payroll_1Routes);
router.use(payroll_2Routes);
router.use(payroll_3Routes);
router.use(payroll_4Routes);
router.use(deductions_1Routes);
router.use(deductions_2Routes);
router.use(advances_1Routes);
router.use(advances_2Routes);
router.use(advanceRequestsRoutes);
router.use(branchManagersRoutes);
router.use(requests_1Routes);
router.use(requests_2Routes);
router.use(hiringRoutes);
router.use(hr_reportsRoutes);
router.use(shift_grid_mergeRoutes);

export default router;
